export const NUM_RESULTS = 50;

export const filterOptions = {
    divisions: [
        {value: 1, label: '1'},
        {value: 2, label: '2'},
        {value: 3, label: '3'},
    ],
    classes: [
        {value: 1, label: 'FR'},
        {value: 2, label: 'SO'},
        {value: 3, label: 'JR'},
        {value: 4, label: 'SR'},
        {value: 5, label: 'GR'},
    ],
    positions: [
        {value: 'QB', label: 'QB'}, 
        {value: 'WR', label: 'WR'}, 
        {value: 'OL', label: 'OL'}, 
        {value: 'RB', label: 'RB'}, 
        {value: 'TE', label: 'TE'}, 
        {value: 'C', label: 'C'}, 
        {value: 'OT', label: 'OT'}, 
        {value: 'FB', label: 'FB'}, 
        {value: 'DL', label: 'DL'}, 
        {value: 'DT', label: 'DT'}, 
        {value: 'DE', label: 'DE'}, 
        {value: 'LB', label: 'LB'}, 
        {value: 'DB', label: 'DB'}, 
        {value: 'CB', label: 'CB'}, 
        {value: 'S', label: 'S'},
        {value: 'P', label: 'P'}, 
        {value: 'K', label: 'K'}, 
        {value: 'LS', label: 'LS'},
    ]
};

const baseSportPositionOptions = {
    FOOTBALL: [
        {value: 'QB', label: 'QB'}, 
        {value: 'WR', label: 'WR'}, 
        {value: 'OL', label: 'OL'}, 
        {value: 'RB', label: 'RB'}, 
        {value: 'TE', label: 'TE'}, 
        {value: 'C', label: 'C'}, 
        {value: 'OT', label: 'OT'}, 
        {value: 'FB', label: 'FB'}, 
        {value: 'DL', label: 'DL'}, 
        {value: 'DT', label: 'DT'}, 
        {value: 'DE', label: 'DE'}, 
        {value: 'LB', label: 'LB'}, 
        {value: 'DB', label: 'DB'}, 
        {value: 'CB', label: 'CB'}, 
        {value: 'S', label: 'S'},
        {value: 'P', label: 'P'}, 
        {value: 'K', label: 'K'}, 
        {value: 'LS', label: 'LS'},
    ],
    BASEBALL: [
        {value: 'P', label: 'P'}, 
        {value: 'C', label: 'C'}, 
        {value: 'INF', label: 'INF'}, 
        {value: 'OF', label: 'OF'}, 
        {value: 'UT', label: 'UT'},
        {value: '1B', label: '1B'},
        {value: '2B', label: '2B'},
        {value: '3B', label: '3B'},
        {value: 'SS', label: 'SS'},
        {value: 'LF', label: 'LF'},
        {value: 'CF', label: 'CF'},
        {value: 'RF', label: 'RF'},
        {value: 'DH', label: 'DH'},
    ],
    BASKETBALL: [
        {value: 'F', label: 'F'},
        {value: 'G', label: 'G'},
        {value: 'C', label: 'C'},
    ],
    HOCKEY: [
        {value: 'G', label: 'G'},
        {value: 'D', label: 'D'},
        {value: 'F', label: 'F'},
    ],
    SOCCER: [
        {value: 'GK', label: 'GK'},
        {value: 'D', label: 'D'},
        {value: 'M', label: 'M'},
        {value: 'F', label: 'F'},
    ],
    LACROSSE: [
        {value: 'M', label: 'M'},
        {value: 'FO', label: 'FO'},
        {value: 'DM', label: 'DM'},
        {value: 'ATT', label: 'ATT'},
        {value: 'D', label: 'D'},
        {value: 'M', label: 'M'},
        {value: 'GK', label: 'GK'},
    ],
    VOLLEYBALL: [
        {value: 'L', label: 'L'},
        {value: 'MB', label: 'MB'},
        {value: 'OH', label: 'OH'},
        {value: 'OPP', label: 'OPP'},
        {value: 'S', label: 'S'},
        {value: 'RS', label: 'RS'},
        {value: 'DS', label: 'DS'},
    ],
    FIELD_HOCKEY: [
        {value: 'M', label: 'M'},
        {value: 'GK', label: 'GK'},
        {value: 'F', label: 'F'},
        {value: 'B', label: 'B'},
    ],
    SOFTBALL: [
        {value: 'C', label: 'C'},
        {value: 'INF', label: 'INF'},
        {value: 'OF', label: 'OF'},
        {value: 'SP/RP', label: 'SP/RP'},
        {value: 'RP', label: 'RP'},
        {value: 'UT', label: 'UT'},
        {value: 'SS', label: 'SS'},
    ]
}


export const advancedFilterOperators = {    
    gt: {value: 'gt', label: 'Greater than'},
    lt: {value: 'lt', label: 'Less than'},
    eq: {value: 'eq', label: 'Equal'},
};

const baseSportStatOptions = {
    FOOTBALL: {
        'general': [
            'all_purpose_plays',
            'all_purpose_yds',
            'all_purpose_yds_per_game',
            'games_played',
            'games_started',
            'points',
            'touchdowns',
        ],
        'offensive': [
            'completion_pct',
            'completions_per_game',
            'first_downs',
            'first_downs_passing',
            'first_downs_rushing',
            'fumbles_lost',
            'interceptions',
            'pass_attempts',
            'passing_eff',
            'passing_tds',
            'passing_yds',
            'passing_yds_per_game',
            'penalties',
            'penalties_per_game',
            'penalty_yds',
            'penalty_yds_per_game',
            'plays',
            'receiving_longest',
            'receiving_tds',
            'receiving_yds',
            'receiving_yds_per_game',
            'receptions',
            'receptions_per_game',
            'redzone_attempts',
            'redzone_passing_tds',
            'redzone_pts',
            'redzone_rushing_tds',
            'redzone_scores',
            'rush_attempts',
            'rush_net_yds',
            'rush_yds_per_game',
            'rushing_longest',
            'rushing_tds',
            'rushing_yds',
            'rushing_yds_lost',
            'third_att',
            'third_conv',
            'total_offensive_plays',
            'total_offensive_yds',
            'total_offensive_yds_per_game',
            'total_offensive_yds_per_play',
            'yds',
            'yds_per_completion',
            'yds_per_play',
            'yds_per_reception',
            'yds_per_rush',
        ],
        'defensive': [
            'blocked',
            'fumbles_forced',
            'fumbles_recovered',
            'fumbles_returned',
            'fumbles_returned_tds',
            'interception_yds',
            'interceptions',
            'interceptions_returned_tds',
            'pass_breakups',
            'passes_defended',
            'pts_off_turnover',
            'redzone_end_downs',
            'redzone_end_interceptions',
            'sack_yds',
            'sacks_assisted',
            'sacks_solo',
            'sacks_unassisted',
            'safeties',
            'tackle_yds',
            'tackles',
            'tackles_assisted',
            'tackles_for_loss_assisted',
            'tackles_for_loss_solo',
            'tackles_solo',
        ],
        'special': [
            'fc_yds',
            'fga1_19',
            'fga20_29',
            'fga30_39',
            'fga40_49',
            'fga50_59',
            'fga60',
            'fgm1_19',
            'fgm20_29',
            'fgm30_39',
            'fgm40_49',
            'fgm50_59',
            'fgm60',
            'field_goal_blocks_allowed',
            'field_goals',
            'field_goals_attempted',
            'field_goals_made',
            'fumble_return_pat',
            'kick_pat',
            'kick_return_pat',
            'kickoff_return_tds',
            'kickoff_return_yds',
            'kickoff_returns',
            'kickoff_touchbacks',
            'kickoff_yds',
            'kickoffs',
            'longest_fgm',
            'net_kickoff_yds',
            'net_punt_yds',
            'onside_attempts',
            'pass_2pt_att',
            'pass_2pt_conv',
            'pat_att',
            'punt_longest',
            'punt_return_tds',
            'punt_return_yds',
            'punt_returns',
            'punt_touchbacks',
            'punt_yds',
            'punts',
            'punts_inside_twenty',
            'receiving_pat',
            'redzone_end_field_goal',
            'redzone_end_fumble',
            'redzone_fg_made',
            'rush_2pt_att',
            'rush_pat',
            'successful_onside_kicks',
        ]

    },
    BASEBALL: {
        'general': [
            'games_played',
            'games_started',
        ],
        'hitting': [
            'batting_average',
            'on_base_percent',
            'slugging_percent',
            'runs',
            'at_bats',
            'hits',
            'doubles',
            'triples',
            'total_bases',
            'homeruns',
            'runs_batted_in',
            'walks',
            'hit_by_pitch',
            'sf',
            'sh',
            'strikeouts',
            'opposite_dp',
            'caught_stealing',
            'picked',
            'stolen_bases',
            'intentional_walks',
            'rbi_2_outs',
        ],
        'pitching': [
            'appearances',
            'games_saved',
            'era',
            'innings_pitched',
            'cg',
            'earned_runs',
            'strikeouts',
            'sho',
            'batters_faced',
            'poab',
            'doubles_allowed',
            'triples_allowed',
            'balks',
            'homeruns_allowed',
            'wp',
            'hit_batters',
            'inh_runners',
            'inh_runners_scored',
            'sha',
            'sfa',
            'pitches_thrown',
            'groundouts',
            'flyouts',
            'wins',
            'losses',
            'saves',
            'kl',
            'pickoffs',
            
        ],
        'fielding': [
            'po',
            'a',
            'tc',
            'errors',
            'fielding_percentage',
            'ci',
            'pb',
            'sba',
            'csb',
            'idp',
            'tp',
        ]
    },
    BASKETBALL: {
        'general': [
            'games_played',
            'games',
            'minutes_played',
            'total_rebounds',
            'personal_fouls',
            'disqualifying_fouls',
            'double_doubles',
            'technical_fouls',
            'triple_doubles',
        ],
        'offensive': [
            'field_goals_made',
            'field_goals_attempted',
            'field_goal_percentage',
            'three_point_field_goals',
            'three_point_field_goals_attempted',
            'three_point_field_goal_percentage',
            'free_throws',
            'free_throw_attempts',
            'free_throw_percentage',
            'points',
            'average_points',
            'offensive_rebounds',
            'assists',
            'turnovers',
        ],
        'defensive': [
            'defensive_rebounds',
            'steals',
            'blocks',
        ]
    },
    HOCKEY: {
        'general': [
            'shootouts',
            'hat_tricks',
            'faceoffs_won',
            'faceoffs_lost',
            'faceoff_percentage',
            'penalties',
            'penalty_minutes',
            'games_miscellaneous',
            'disqualifications',
            'plus_minus',
        ],
        'offensive': [
            'goals',
            'assists',
            'points',
            'shots',
            'short_handed_goals',
            'empty_net_goals',
            'game_winning_goals',
            'game_tying_goals',
            'overtime_goals',
            'power_play_goals',
            'power_play_assists',
            'power_play_shots',
            'power_play_percentage',
            'power_play_shot_attempts',
        ],
        'goalie': [
            'goalie_minutes',
            'goals_against',
            'power_play_goals_against',
            'saves',
            'save_percentage',
            'shutouts',
            'goalie_won',
            'goalie_loss',
            'goalie_tied',
            'goals_against_average',
        ]
    },
    SOCCER: {
        'general': [
            'games_played',
            'games',
            'fouls',
            'red_cards',
            'yellow_cards',
            'penalty_kicks',
            'penalty_kick_attempts',
            'corners',
        ],
        'offensive': [
            'goals',
            'assists',
            'points',
            'shot_attempts',
            'shots_on_goal',
            'golden_goals',
            'game_winning_goals',
        ],
        'defensive': [
            'goals_conceded',
            'goalie_games_played',
            'goalie_minutes_played',
            'goals_allowed',
            'goals_allowed_average',
            'saves',
            'save_percentage',
            'shutouts',
            'combined_shutouts',
            'goalie_wins',
            'goalie_losses',
            'goalie_ties',
            'defensive_saves',
        ]
    },
    LACROSSE: {
        'general': [
            'games_played',
            'games',
            'fouls',
            'games_started',
            'ground_balls',
            'turnovers',
            'free_position_shots',
            'free_position_goals',
            'red_cards',
            'yellow_cards',
            'clears',
            'clear_attempts',
            'man_up_games',
            'man_down_games',
            'faceoffs_won',
            'faceoffs_taken',
            'faceoffs_percentage',
            'penalties',
            'penalty_time',
            'clear_percentage',
        ],
        'offensive': [
            'goals',
            'assists',
            'points',
            'shots',
            'shot_percentage',
            'shots_on_goal',
            'shot_on_goal_percentage',
            'game_winning_goals',
            'points_per_game',
            'short_handed_goals',
            'draw_controls',
            'attempts',
            'overtime_goals',
        ],
        'defensive': [
            'caused_turnovers',
            'goalie_games_played',
            'goalie_mins',
            'goals_allowed',
            'goals_against_average',
            'saves',
            'save_percentage',
        ]
    },
    VOLLEYBALL: {
        'general': [
            'games_played',
            'minutes_played',
            'matches_started',
            'errors',
            'triple_double',
        ],
        'offensive': [
            'serves',
            'kills',
            'total_attacks',
            'hit_percentage',
            'assists',
            'aces',
            'points',
        ],
        'defensive': [
            'serve_error',
            'digs',
            'reception_errors',
            'block_solos',
            'block_assists',
            'block_errors',
            'ball_handling_errors',
        ]
    },
    FIELD_HOCKEY: {
        'general': [
            'games_played',
            'fouls',
            'red_cards',
            'yellow_cards',
            'green_cards',
            'minutes',
            'corners',
            'penalty_strokes',
            'penalty_strokes_allowed',
        ],
        'offensive': [
            'goals',
            'assists',
            'points',
            'shot_attempts',
            'game_winners',
        ],
        'defensive': [
            'goalie_games_played',
            'goalie_games_started',
            'goals_against',
            'goals_against_average',
            'saves',
            'save_percentage',
            'shutouts',
            'goalie_wins',
            'goalie_losses',
            'defensive_saves',
        ]
    },
    SOFTBALL: {
        'general': [
            'games_played',
            'games_started',
            'games',
        ],
        'hitting': [
            'batting_average',
            'on_base_percent',
            'slugging_percent',
            'runs',
            'at_bats',
            'hits',
            'doubles',
            'triples',
            'total_bases',
            'homeruns',
            'runs_batted_in',
            'walks',
            'hit_by_pitch',
            'sf',
            'sh',
            'strikeouts',
            'strikeouts_looking',
            'opposite_dp',
            'caught_stealing',
            'picked',
            'stolen_bases',
            'intentional_walks',
            'rbi_2_outs',
            'double_plays',
            'groundout_double_plays',
            'cso',
        ],
        'pitching': [
            'appearances',
            'games_saved',
            'era',
            'earned_runs',
            'innings_pitched',
            'cg',
            'strikeouts',
            'sho',
            'batters_faced',
            'hits_allowed',
            'poab',
            'doubles_allowed',
            'triples_allowed',
            'balks',
            'homeruns_allowed',
            'wp',
            'hit_batters',
            'inh_runners',
            'inh_runners_scored',
            'sha',
            'sfa',
            'pitches_thrown',
            'groundouts',
            'flyouts',
            'wins',
            'losses',
            'saves',
            'kl',
            'pickoffs',
            'wild_pitches',
            'cia',
        ],
        'fielding': [
            'po',
            'a',
            'tc',
            'errors',
            'fielding_percentage',
            'ci',
            'pb',
            'sba',
            'csb',
            'idp',
            'tp',
        ]
    }
}

export const sportOptions = [
    {value: 'FOOTBALL', label: 'Football'},
    {value: 'BASEBALL', label: 'Baseball'},
    {value: 'MENS_BASKETBALL', label: "Men's Basketball"},
    {value: 'WOMENS_BASKETBALL', label: "Women's Basketball"},
    {value: 'MENS_ICE_HOCKEY', label: "Men's Ice Hockey"},
    {value: 'WOMENS_ICE_HOCKEY', label: "Women's Ice Hockey"},
    {value: 'MENS_SOCCER', label: "Men's Soccer"},
    {value: 'WOMENS_SOCCER', label: "Women's Soccer"},
    {value: 'MENS_VOLLEYBALL', label: "Men's Volleyball"},
    {value: 'WOMENS_VOLLEYBALL', label: "Women's Volleyball"},
    {value: 'MENS_LACROSSE', label: "Men's Lacrosse"},
    {value: 'WOMENS_LACROSSE', label: "Women's Lacrosse"},
    {value: 'FIELD_HOCKEY', label: 'Field Hockey'},
    {value: 'SOFTBALL', label: 'Softball'},
];

export const sportPositionOptions = {
    FOOTBALL: baseSportPositionOptions.FOOTBALL,
    BASEBALL: baseSportPositionOptions.BASEBALL,
    MENS_BASKETBALL: baseSportPositionOptions.BASKETBALL,
    WOMENS_BASKETBALL: baseSportPositionOptions.BASKETBALL,
    MENS_ICE_HOCKEY: baseSportPositionOptions.HOCKEY,
    WOMENS_ICE_HOCKEY: baseSportPositionOptions.HOCKEY,
    MENS_SOCCER: baseSportPositionOptions.SOCCER,
    WOMENS_SOCCER: baseSportPositionOptions.SOCCER,
    MENS_LACROSSE: baseSportPositionOptions.LACROSSE,
    WOMENS_LACROSSE: baseSportPositionOptions.LACROSSE,
    MENS_VOLLEYBALL: baseSportPositionOptions.VOLLEYBALL,
    WOMENS_VOLLEYBALL: baseSportPositionOptions.VOLLEYBALL,
    FIELD_HOCKEY: baseSportPositionOptions.FIELD_HOCKEY,
    SOFTBALL: baseSportPositionOptions.SOFTBALL,
}

export const sportStatOptions = {
    FOOTBALL: baseSportStatOptions.FOOTBALL,
    BASEBALL: baseSportStatOptions.BASEBALL,
    MENS_BASKETBALL: baseSportStatOptions.BASKETBALL,
    WOMENS_BASKETBALL: baseSportStatOptions.BASKETBALL,
    MENS_ICE_HOCKEY: baseSportStatOptions.HOCKEY,
    WOMENS_ICE_HOCKEY: baseSportStatOptions.HOCKEY,
    MENS_SOCCER: baseSportStatOptions.SOCCER,
    WOMENS_SOCCER: baseSportStatOptions.SOCCER,
    MENS_LACROSSE: baseSportStatOptions.LACROSSE,
    WOMENS_LACROSSE: baseSportStatOptions.LACROSSE,
    MENS_VOLLEYBALL: baseSportStatOptions.VOLLEYBALL,
    WOMENS_VOLLEYBALL: baseSportStatOptions.VOLLEYBALL,
    FIELD_HOCKEY: baseSportStatOptions.FIELD_HOCKEY,
    SOFTBALL: baseSportStatOptions.SOFTBALL
}
