export const NUM_RESULTS = 50;

export const filterOptions = {
    divisions: [
        {value: [1, 2, 3], label: 'All'},
        {value: 1, label: '1'},
        {value: 2, label: '2'},
        {value: 3, label: '3'},
    ],
    classes: [
        {value: [1, 2, 3, 4, 5], label: 'All'},
        {value: 1, label: 'FR'},
        {value: 2, label: 'SO'},
        {value: 3, label: 'JR'},
        {value: 4, label: 'SR'},
        {value: 5, label: 'GR'},
    ],
    positions: [
        {value: ['QB', 'WR', 'OL', 'RB', 'TE', 'C', 'OT', 'FB', 'DL', 'DT', 'DE', 'LB', 'DB', 'CB', 'S', 'P', 'K', 'LS'], label: 'All'},
        {value: 'QB', label: 'QB'}, 
        {value: 'WR', label: 'WR'}, 
        {value: 'OL', label: 'OL'}, 
        {value: 'RB', label: 'RB'}, 
        {value: 'TE', label: 'TE'}, 
        {value: 'C', label: 'C'}, 
        {value: 'OT', label: 'OT'}, 
        {value: 'FB', label: 'FB'}, 
        {value: 'DL', label: 'DL'}, 
        {value: 'DT', label: 'DT'}, 
        {value: 'DE', label: 'DE'}, 
        {value: 'LB', label: 'LB'}, 
        {value: 'DB', label: 'DB'}, 
        {value: 'CB', label: 'CB'}, 
        {value: 'S', label: 'S'},
        {value: 'P', label: 'P'}, 
        {value: 'K', label: 'K'}, 
        {value: 'LS', label: 'LS'},
    ]
};

export const advancedFilterOperators = {    
    gt: {value: 'gt', label: 'Greater than'},
    lt: {value: 'lt', label: 'Less than'},
    eq: {value: 'eq', label: 'Equal'},
};

export const sportOptions = [
    {value: "football", label: "Football"},
    {value: "baseball", label: "Baseball"},
    {value: "soccer", label: "Soccer"},
];

export const sportStatOptions = {
    football: {
        'general': [
            'all_purpose_plays',
            'all_purpose_yds',
            'all_purpose_yds_per_game',
            'games_played',
            'games_started',
            'points',
            'touchdowns',
        ],
        'offensive': [
            'completion_pct',
            'completions_per_game',
            'first_downs',
            'first_downs_passing',
            'first_downs_rushing',
            'fumbles_lost',
            'interceptions',
            'pass_attempts',
            'passing_eff',
            'passing_tds',
            'passing_yds',
            'passing_yds_per_game',
            'penalties',
            'penalties_per_game',
            'penalty_yds',
            'penalty_yds_per_game',
            'plays',
            'receiving_longest',
            'receiving_tds',
            'receiving_yds',
            'receiving_yds_per_game',
            'receptions',
            'receptions_per_game',
            'redzone_attempts',
            'redzone_passing_tds',
            'redzone_pts',
            'redzone_rushing_tds',
            'redzone_scores',
            'rush_attempts',
            'rush_net_yds',
            'rush_yds_per_game',
            'rushing_longest',
            'rushing_tds',
            'rushing_yds',
            'rushing_yds_lost',
            'third_att',
            'third_conv',
            'total_offensive_plays',
            'total_offensive_yds',
            'total_offensive_yds_per_game',
            'total_offensive_yds_per_play',
            'yds',
            'yds_per_completion',
            'yds_per_play',
            'yds_per_reception',
            'yds_per_rush',
        ],
        'defensive': [
            'blocked',
            'fumbles_forced',
            'fumbles_recovered',
            'fumbles_returned',
            'fumbles_returned_tds',
            'interception_yds',
            'interceptions',
            'interceptions_returned_tds',
            'pass_breakups',
            'passes_defended',
            'pts_off_turnover',
            'redzone_end_downs',
            'redzone_end_interceptions',
            'sack_yds',
            'sacks_assisted',
            'sacks_solo',
            'sacks_unassisted',
            'safeties',
            'tackle_yds',
            'tackles',
            'tackles_assisted',
            'tackles_for_loss_assisted',
            'tackles_for_loss_solo',
            'tackles_solo',
        ],
        'special': [
            'fc_yds',
            'fga1_19',
            'fga20_29',
            'fga30_39',
            'fga40_49',
            'fga50_59',
            'fga60',
            'fgm1_19',
            'fgm20_29',
            'fgm30_39',
            'fgm40_49',
            'fgm50_59',
            'fgm60',
            'field_goal_blocks_allowed',
            'field_goals',
            'field_goals_attempted',
            'field_goals_made',
            'fumble_return_pat',
            'kick_pat',
            'kick_return_pat',
            'kickoff_return_tds',
            'kickoff_return_yds',
            'kickoff_returns',
            'kickoff_touchbacks',
            'kickoff_yds',
            'kickoffs',
            'longest_fgm',
            'net_kickoff_yds',
            'net_punt_yds',
            'onside_attempts',
            'pass_2pt_att',
            'pass_2pt_conv',
            'pat_att',
            'punt_longest',
            'punt_return_tds',
            'punt_return_yds',
            'punt_returns',
            'punt_touchbacks',
            'punt_yds',
            'punts',
            'punts_inside_twenty',
            'receiving_pat',
            'redzone_end_field_goal',
            'redzone_end_fumble',
            'redzone_fg_made',
            'rush_2pt_att',
            'rush_pat',
            'successful_onside_kicks',
        ]
    }
}
